[[permission]]
identifier = "default"
description = "Default permissions"
commands.allow = [
    "search_emails",
    "get_stats",
    "get_graph",
    "start_sync",
    "get_logs",
    "get_config",
    "save_config",
    "save_log_cmd",
    "get_email",
    "list_prompts",
    "save_prompt",
    "draft_reply",
    "get_models"
]
